#!/bin/bash
make clean
echo Building
echo oven1...
make oven=1
make clean > /dev/null
echo oven2...
make oven=2
make clean > /dev/null
echo oven3...
make oven=3
make clean > /dev/null
echo oven4...
make oven=4
make clean > /dev/null
echo oven5...
make oven=5
make clean > /dev/null
echo oven6...
make oven=6
echo Done
